version: 2.1

jobs:
  Build:
    docker:
      - image: cimg/rust:1.50.0
    steps:
      - checkout
      - run:
          name: "Build"
          command: "cargo build"

workflows:
  test-cargo:
    jobs:
      - Build
