name: Rust

on: [push, pull_request, pull_request_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:

    - name: Build (Ubuntu)
      run: cargo build